name: ${project.name}
version: ${project.version}
author: CuzIm1Tigaaa
main: ${project.groupId}.Spectator
api-version: 1.16
softdepend: ['Multiverse-Core', 'PlaceholderAPI']
commands:
  spectate:
    aliases: [ spec ]
    usage: /spectate [target]
  spectatecycle:
    aliases: [ speccycle ]
    usage: /spectatecycle <start|stop> ...
  spectatehere:
    aliases: [ spechere,spech ]
    usage: /spectatehere
  spectatelist:
    aliases: [ speclist ]
    usage: /spectatelist
  spectatereload:
    aliases: [ specreload,specrl ]
    usage: /spectatereload
  unspectate:
    aliases: [ unspec ]
    usage: /unspectate [Player] [true|false]
permissions:
  spectator.commands.spectatereload:
    description: Permission for /spectatereload
    default: false
  spectator.commands.unspectate:
    description: Permission for /unspectate
    default: false
  spectator.commands.admin:
    description: Permission for all admin commands
    default: op
    children:
      spectator.commands.spectatereload: true
      spectator.commands.unspectate: true
  spectator.commands.spectate:
    description: Permission for /spectate
    default: false
  spectator.commands.spectateothers:
    description: Permission for /spectate [player]
    default: false
  spectator.commands.spectatehere:
    description: Permission for /spectatehere
    default: false
  spectator.commands.spectatelist:
    description: Permission for /spectatelist
    default: false
  spectator.commands.spectatecycle.default:
    description: Permission for /spectatecycle
    default: false
  spectator.commands.spectatecycle.stopOthers:
    description: Permission for /spectatecycle stop <Player>
    default: false
  spectator.commands.spectatecycle.*:
    description: Permission for all SpectateCycle commands
    default: false
    children:
      spectator.commands.spectatecycle.default: true
      spectator.commands.spectatecycle.stopOthers: true
  spectator.commands.*:
    description: Permission for all commands (CycleOnly excluded!)
    default: op
    children:
      spectator.commands.admin: true
      spectator.commands.spectate: true
      spectator.commands.spectateothers: true
      spectator.commands.spectatehere: true
      spectator.commands.spectatelist: true
      spectator.commands.spectatecycle.*: true
  spectator.bypass.tablist:
    description: Permission to see hidden players in Spigot Tablist
    default: false
  spectator.bypass.spectated:
    description: Permission to not get spectated by other players
    default: false
  spectator.bypass.spectateall:
    description: Permission to spectate players even though they have the permission 'spectator.bypass.spectated'
    default: false
  spectator.bypass.notify:
    description: Permission to bypass sending notification message when activated in config.yml
    default: false
  spectator.bypass.*:
    description: Permission for all .bypass Permissions
    default: op
    children:
      spectator.bypass.tablist: true
      spectator.bypass.spectated: true
      spectator.bypass.spectateall: true
      spectator.bypass.notify: true
  spectator.utils.openenderchest:
    description: Permission to see the enderchest when opened by the current target during spectating
    default: false
  spectator.utils.opencontainer:
    description: Permission to see contents of containers opened by the current target during spectating
    default: false
  spectator.utils.mirrorinventory:
    description: Permission to see other players Inventory during spectating
    default: false
  spectator.utils.mirroreffects:
    description: Permission to see other players Inventory during spectating
    default: false
  spectator.utils.hidetab:
    description: Permission to be hidden in Spigot Tablist
    default: false
  spectator.utils.*:
    description: Permission for all .utils Permissions
    default: op
    children:
      spectator.utils.openenderchest: true
      spectator.utils.opencontainer: true
      spectator.utils.mirrorinventory: true
      spectator.utils.mirroreffects: true
      spectator.utils.hidetab: true
  spectator.notify.update:
    description: Permission to get an alert when an update is available
    default: op
  spectator.*:
    description: Permission for every Permission (CycleOnly excluded!)
    default: false
    children:
      spectator.commands.*: true
      spectator.bypass.*: true
      spectator.utils.*: true
      spectator.notify: true